apiVersion: v1
kind: Pod
metadata:
  namespace: default
  name: webpage-server
  labels:
    name: app
spec:
  containers:
  - name: nginx
    image: nginx:1.15
    ports:
      - containerPort: 80
    volumeMounts:
        - name: webpage
          mountPath: /var/www/html
  volumes:
    - name: webpage
      persistentVolumeClaim:
        claimName: webpage
